### ISSUE TITLE
About YOLOv7

### ISSUE THREAD

**Issue by jinfagang** [jinfagang/yolov7#41]
If you are new to YOLOv7, there are 2 things you need to know:

1. YOLOv7 is not a simple enhancement upon YOLO, it was meaningless, instead, we are exploring the potential power of **transformers** model combination with anchor or anchor free design detectors, also, we are exploring on STACK instance head or key points head or semantic segmentation head to a **unfied** multi-tasking network;
2. Contribution is very welcomed, please join our WeChat group if you want learn more!

At last, this is my vision of YOLOv7:

1. Building a training framework with detectron2, not just for detection, but as many tasks as possible;
2. Building a mature deploy chain, from training to deployment. I am keeping add TensorRT, tvm, ncnn deployment for the YOLOv7 trained model;
3. Let's pushing YOLOv7 detector's mAP to a higher standard!
4. Every single contributor I will add to README so that your work can be seen.

**Comment by anh-viet-dang** [comment]
I think we have some conflict about name of yolo version
I think this [repo](https://github.com/WongKinYiu/yolov7/) is the official yolov7. Because I found the paper of yolov7 [here](https://paperswithcode.com/paper/yolov7-trainable-bag-of-freebies-sets-new).       More over, the authors of [that yolov7](https://github.com/WongKinYiu/yolov7/) are also the authors of [yolov4](https://arxiv.org/pdf/2004.10934v1.pdf), [scaled yolov4](https://arxiv.org/pdf/2011.08036v2.pdf) and [yolor](https://arxiv.org/pdf/2105.04206v1.pdf)

**Comment by jinfagang** [comment]
Please look at the repo creating time.... **WE ARE MUCH MORE EARLIER**

**Comment by jinfagang** [comment]
@akashAD98 No, I also become confusion why they using yolov7 after we launch this repo. I will consider change the name, but not for they release paper, it becomes of **I don't want they messed up my plan**.

**Comment by akashAD98** [comment]
@jinfagang give i think you need to give name  yolov8 & launch with all technical blog+papaer, it will be good & there will be no any confusion. also it would be grate if you publish your score on coco dataset to compare MAP  performance

**Comment by Zeeshann1** [comment]
I tried to join Yolov7 WeChat group but QR code is expired maybe. Could you please add me in Yolov7 WeChat group? Thank you.
My WeChat: zeeshanHyderAbro

**Comment by jinfagang** [comment]
Join discord. https://discord.gg/2E8AfjaEXM
